server:
  port: 8082
  servlet:
    context-path: /
    encoding:
      charset: utf-8
      enabled: true

spring:
  config:
    activate:
      on-profile: production
    import: 'aws-parameterstore:'

  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/photogram?serverTimezone=Asia/Seoul
    username: ${mariadb.username}
    password: ${mariadb.password}

  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: none
      use-new-id-generator-mappings: false
    open-in-view: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  servlet:
    multipart:
      enabled: true
      max-file-size: 2MB

  security:
    user:
      name: test
      password: 1234

    oauth2:
      client:
        registration:
          google:
            client-id: ${google.client.id}
            client-secret: ${google.client.secret}
            scope:
              - email
              - profile
          facebook:
            client-id: ${facebook.client.id}
            client-secret: ${facebook.client.secret}
            scope:
            - public_profile
            - email
          kakao:
            client-id: ${kakao.client.id}
            redirect-uri: "http://localhost:8082/login/oauth2/code/kakao"
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            scope:
            - profile_nickname
            - profile_image
            - account_email
            - gender
            client-name: Kakao
          naver:
            client-id: ${naver.client.id}
            client-secret: ${naver.client.secret}
            redirect-uri: "http://localhost:8082/login/oauth2/code/naver"
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            scope: name,email
            client-name: Naver
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
aws:
  paramstore:
    enabled: true
    prefix: /config
    profile-separator: _
    name: application

file:
  path: /mnt/upload/

